zxf.lo: /home/svn/php-7.2.2/ext/zxf/zxf.c
	$(LIBTOOL) --mode=compile $(CC) -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/home/svn/php-7.2.2/ext/zxf $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/svn/php-7.2.2/ext/zxf/zxf.c -o zxf.lo 
$(phplibdir)/zxf.la: ./zxf.la
	$(LIBTOOL) --mode=install cp ./zxf.la $(phplibdir)

./zxf.la: $(shared_objects_zxf) $(ZXF_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_zxf) $(ZXF_SHARED_LIBADD)

